//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPoeClinica
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Cita
    {
        public int ID_Detalle { get; set; }
        public int ID_Cita { get; set; }
        public int ID_Medico { get; set; }
        public int ID_Expediente { get; set; }
    
        public virtual Citas_Medicas Citas_Medicas { get; set; }
        public virtual Medicos Medicos { get; set; }
        public virtual Expedientes Expedientes { get; set; }
    }
}
