//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPoeClinica
{
    using System;
    using System.Collections.Generic;
    
    public partial class Especialidad_Medico
    {
        public int ID_Espec_Medico { get; set; }
        public int ID_MEDICO { get; set; }
        public int ID_ESPECIALIDAD { get; set; }
    
        public virtual Especialidad Especialidad { get; set; }
        public virtual Medicos Medicos { get; set; }
    }
}
