//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPoeClinica
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expedientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Expedientes()
        {
            this.Detalle_Cita = new HashSet<Detalle_Cita>();
        }
    
        public int ID_Expediente { get; set; }
        public int ID_Paciente { get; set; }
        public Nullable<System.DateTime> Afilacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Cita> Detalle_Cita { get; set; }
        public virtual Pacientes Pacientes { get; set; }
    }
}
